const Main = () => {
   return(
    <div>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
        <h1>scrolldown</h1>
    </div>
   )
}

export default Main;